# Generated by Django 3.0.3 on 2020-05-25 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0002_add_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bug',
            options={
                'permissions': (
                    ('add_bugtag', 'can add bug tag'), ('delete_bugtag', 'can delete bug tag')
                )
            },
        ),
    ]
