files:
  - source: /tcms/locale/en/LC_MESSAGES/django.po
    translation: /tcms/locale/%locale_with_underscore%/LC_MESSAGES/django.po
  - source: /tcms/locale/en/LC_MESSAGES/djangojs.po
    translation: /tcms/locale/%locale_with_underscore%/LC_MESSAGES/djangojs.po
