apiVersion: v1
kind: Service
metadata:
  name: kiwi-db
  labels:
    app: kiwi
spec:
  ports:
    - port: 5432
  selector:
    app: kiwi
    tier: postgres
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: kiwi-db
  labels:
    app: kiwi
spec:
  selector:
    matchLabels:
      app: kiwi
      tier: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kiwi
        tier: postgres
    spec:
      containers:
      - image: postgres:alpine
        name: postgres
        env:
          - name: POSTGRES_DB
            value: kiwi
          - name: POSTGRES_PASSWORD
            value: kiwi-1s-aw3s0m3
          - name: POSTGRES_USER
            value: kiwi
        ports:
          - containerPort: 5432
            name: postgres

