#!/usr/bin/env python -i

# readline & tab completion support
import sys, rlcompleter, readline
readline.parse_and_bind("tab: complete")
readline.parse_and_bind("set editing-mode vi")

# import all names
from tcms_api import *
