{{- if and .Values.email.smtp.enabled (not .Values.email.smtp.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kiwi.fullname" . }}-smtp
  labels:
    {{- include "kiwi.labels" . | nindent 4 }}
type: Opaque
stringData:
  smtp-user: {{ .Values.email.smtp.user | quote }}
  smtp-password: {{ .Values.email.smtp.password | quote }}
{{- end }}
