# Generated by Django 2.0.7 on 2018-07-25 14:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('profiles', '0001_initial'),
                ('profiles', '0002_remove_unused_models'),
                ('profiles', '0003_drop_meta_db_name'),
                ('profiles', '0004_remove_bookmarks')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False,
                                        verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, default='', max_length=128)),
                ('url', models.URLField(blank=True, default='')),
                ('im', models.CharField(blank=True, default='', max_length=128)),
                ('im_type_id', models.IntegerField(blank=True, default=1, null=True)),
                ('address', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('user', models.OneToOneField(on_delete=models.deletion.CASCADE,
                                              related_name='profile',
                                              to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
