# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 11:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usergroupmap',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='usergroupmap',
            name='group',
        ),
        migrations.RemoveField(
            model_name='usergroupmap',
            name='user',
        ),
        migrations.DeleteModel(
            name='Groups',
        ),
        migrations.DeleteModel(
            name='Profiles',
        ),
        migrations.DeleteModel(
            name='UserGroupMap',
        ),
    ]
