# Generated by Django 2.0.6 on 2018-06-29 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_unused_models'),
    ]

    atomic = False

    operations = [
        migrations.AlterModelTable(
            name='bookmark',
            table=None,
        ),
        migrations.AlterModelTable(
            name='bookmarkcategory',
            table=None,
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table=None,
        ),
    ]
