# Generated by Django 2.0.7 on 2018-07-05 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_drop_meta_db_name'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='bookmark',
            index_together=set(),
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='category',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='site',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='user',
        ),
        migrations.RemoveField(
            model_name='bookmarkcategory',
            name='user',
        ),
        migrations.DeleteModel(
            name='Bookmark',
        ),
        migrations.DeleteModel(
            name='BookmarkCategory',
        ),
    ]
