# Generated by Django 2.1.2 on 2018-10-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    replaces = [
        ('testplans', '0006_delete_testplan_component'),
        ('testplans', '0008_rename_env'),
        ('testplans', '0009_rename_testplantype')
    ]

    dependencies = [
        ('management', '0007_rename_env'),
        ('testplans', '0001_squashed'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testplancomponent',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='testplancomponent',
            name='component',
        ),
        migrations.RemoveField(
            model_name='testplancomponent',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='testplan',
            name='component',
        ),
        migrations.DeleteModel(
            name='TestPlanComponent',
        ),
        migrations.RenameModel(
            old_name='TCMSEnvPlanMap',
            new_name='EnvPlanMap',
        ),
        migrations.AlterField(
            model_name='EnvPlanMap',
            name='group',
            field=models.ForeignKey(on_delete=models.deletion.CASCADE, to='management.EnvGroup'),
        ),
        migrations.AlterField(
            model_name='TestPlan',
            name='env_group',
            field=models.ManyToManyField(through='testplans.EnvPlanMap', to='management.EnvGroup'),
        ),
        migrations.RenameModel(
            old_name='TestPlanType',
            new_name='PlanType',
        ),
        migrations.AlterField(
            model_name='TestPlan',
            name='type',
            field=models.ForeignKey(on_delete=models.deletion.CASCADE, to='testplans.PlanType'),
        ),
    ]
