# Generated by Django 2.1.2 on 2018-10-18 14:44

from django.conf import settings
from django.db import migrations, models


def forward_copy_data(apps, schema_editor):
    TestPlan = apps.get_model('testplans', 'TestPlan')
    TestPlanText = apps.get_model('testplans', 'TestPlanText')

    for test_plan in TestPlan.objects.all():
        latest_text = TestPlanText.objects.filter(plan=test_plan.pk).order_by('-pk').first()
        if latest_text:
            test_plan.plan_text = latest_text.plan_text
            test_plan.save()


class Migration(migrations.Migration):

    replaces = [
        ('testplans', '0016_historicaltestplan'),
        ('testplans', '0017_move_text_into_testplan'),
        ('testplans', '0018_remove_env'),
        ('testplans', '0019_remove_testplantag_user')
    ]

    dependencies = [
        ('testplans', '0003_squashed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='testplan',
            name='plan_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='HistoricalTestPlan',
            fields=[
                ('plan_id', models.IntegerField(blank=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('create_date', models.DateTimeField(blank=True,
                                                     db_column='creation_date',
                                                     editable=False)),
                ('is_active', models.BooleanField(db_column='isactive',
                                                  db_index=True, default=True)),
                ('extra_link', models.CharField(blank=True, default=None,
                                                max_length=1024, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[
                 ('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('author', models.ForeignKey(blank=True, db_constraint=False, null=True,
                                             on_delete=models.deletion.DO_NOTHING, related_name='+',
                                             to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=models.deletion.SET_NULL,
                                                   related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, db_constraint=False, null=True,
                                            on_delete=models.deletion.DO_NOTHING, related_name='+',
                                            to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, db_constraint=False, null=True,
                                             on_delete=models.deletion.DO_NOTHING,
                                             related_name='+', to='testplans.TestPlan')),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True,
                                              on_delete=models.deletion.DO_NOTHING,
                                              related_name='+', to='management.Product')),
                ('product_version', models.ForeignKey(blank=True, db_constraint=False, null=True,
                                                      on_delete=models.deletion.DO_NOTHING,
                                                      related_name='+', to='management.Version')),
                ('type', models.ForeignKey(blank=True, db_constraint=False, null=True,
                                           on_delete=models.deletion.DO_NOTHING, related_name='+',
                                           to='testplans.PlanType')),
                ('plan_text', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'historical test plan',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.AddField(
            model_name='testplan',
            name='plan_text',
            field=models.TextField(blank=True),
        ),

        migrations.RunPython(forward_copy_data),

        migrations.RemoveField(
            model_name='testplantext',
            name='author',
        ),
        migrations.RemoveField(
            model_name='testplantext',
            name='plan',
        ),
        migrations.DeleteModel(
            name='TestPlanText',
        ),
        migrations.RenameField(
            model_name='historicaltestplan',
            old_name='plan_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='testplan',
            old_name='plan_text',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='envplanmap',
            name='group',
        ),
        migrations.RemoveField(
            model_name='envplanmap',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='testplan',
            name='env_group',
        ),
        migrations.DeleteModel(
            name='EnvPlanMap',
        ),
        migrations.RemoveField(
            model_name='testplantag',
            name='user',
        ),
    ]
