# Generated by Django 2.0 on 2017-12-30 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testplans', '0004_remove_model_TestPlanActivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testplanattachment',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='testplanattachment',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='testplan',
            name='attachment',
        ),
        migrations.DeleteModel(
            name='TestPlanAttachment',
        ),
    ]
