# Generated by Django 2.0.1 on 2018-01-30 09:39
# delete the TestPlan.component field and the corresponding
# TestPlanComponent table. Components are attached to TestCases, not
# TestPlans and have never actually been used inside a TestPlan

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testplans', '0001_squashed'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testplancomponent',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='testplancomponent',
            name='component',
        ),
        migrations.RemoveField(
            model_name='testplancomponent',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='testplan',
            name='component',
        ),
        migrations.DeleteModel(
            name='TestPlanComponent',
        ),
    ]
