# Generated by Django 2.1.2 on 2018-10-06 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("testplans", "0005_squashed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaltestplan",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="testplan",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="testplanemailsettings",
            name="auto_to_plan_owner",
        ),
    ]
