# Generated by Django 2.0.1 on 2018-02-01 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testplans', '0006_delete_testplan_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testplan',
            name='tag',
            field=models.ManyToManyField(related_name='plan',
                                         through='testplans.TestPlanTag',
                                         to='management.TestTag'),
        ),
    ]
