# Generated by Django 3.0.2 on 2020-01-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testplans', '0007_notifications_default_true'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltestplan',
            name='create_date',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='historicaltestplan',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
