# Generated by Django 5.2.15 on 2026-06-14 15:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testplans", "0010_alter_historicaltestplan_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaltestplan",
            name="extra_link",
            field=models.URLField(
                blank=True,
                default=None,
                max_length=1024,
                null=True,
                validators=[
                    django.core.validators.URLValidator(
                        schemes=["http", "https", "ftp", "ftps"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="testplan",
            name="extra_link",
            field=models.URLField(
                blank=True,
                default=None,
                max_length=1024,
                null=True,
                validators=[
                    django.core.validators.URLValidator(
                        schemes=["http", "https", "ftp", "ftps"]
                    )
                ],
            ),
        ),
    ]
