# Generated by Django 5.2.11 on 2026-02-18 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testplans', '0010_alter_historicaltestplan_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltestplan',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='testplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
