# Generated by Django 2.0.2 on 2018-02-23 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testplans', '0010_rename_testtag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testplanemailsettings',
            name='notify_on_plan_delete',
        ),
    ]
