# Generated by Django 2.0.4 on 2018-04-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testplans', '0011_remove_testplanemailsettings_notify_on_plan_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testplantext',
            name='checksum',
            field=models.CharField(max_length=64),
        ),
    ]
