# Generated by Django 2.0.6 on 2018-06-26 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testplans', '0013_remove_plan_text_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testplantext',
            name='checksum',
        ),
    ]
