# Generated by Django 2.0.6 on 2018-06-29 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testplans', '0014_remove_testplantext_checksum'),
    ]

    atomic = False

    operations = [
        migrations.AlterModelTable(
            name='envplanmap',
            table=None,
        ),
        migrations.AlterModelTable(
            name='plantype',
            table=None,
        ),
        migrations.AlterModelTable(
            name='testplan',
            table=None,
        ),
        migrations.AlterModelTable(
            name='testplantag',
            table=None,
        ),
        migrations.AlterModelTable(
            name='testplantext',
            table=None,
        ),
    ]
