# Generated by Django 2.0.7 on 2018-07-04 20:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_drop_meta_db_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testplans', '0015_drop_meta_db_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testplan',
            name='plan_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),

        migrations.CreateModel(
            name='HistoricalTestPlan',
            fields=[
                ('plan_id', models.IntegerField(blank=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('create_date', models.DateTimeField(blank=True,
                                                     db_column='creation_date',
                                                     editable=False)),
                ('is_active', models.BooleanField(db_column='isactive',
                                                  db_index=True,
                                                  default=True)),
                ('extra_link', models.CharField(blank=True,
                                                default=None,
                                                max_length=1024,
                                                null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'),
                                                           ('~', 'Changed'),
                                                           ('-', 'Deleted')],
                                                  max_length=1)),
                ('author', models.ForeignKey(blank=True,
                                             db_constraint=False,
                                             null=True,
                                             on_delete=models.DO_NOTHING,
                                             related_name='+',
                                             to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True,
                                                   on_delete=models.SET_NULL,
                                                   related_name='+',
                                                   to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True,
                                            db_constraint=False,
                                            null=True,
                                            on_delete=models.DO_NOTHING,
                                            related_name='+',
                                            to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True,
                                             db_constraint=False,
                                             null=True,
                                             on_delete=models.DO_NOTHING,
                                             related_name='+',
                                             to='testplans.TestPlan')),
                ('product', models.ForeignKey(blank=True,
                                              db_constraint=False,
                                              null=True,
                                              on_delete=models.DO_NOTHING,
                                              related_name='+',
                                              to='management.Product')),
                ('product_version', models.ForeignKey(blank=True,
                                                      db_constraint=False,
                                                      null=True,
                                                      on_delete=models.DO_NOTHING,
                                                      related_name='+',
                                                      to='management.Version')),
                ('type', models.ForeignKey(blank=True,
                                           db_constraint=False,
                                           null=True,
                                           on_delete=models.DO_NOTHING,
                                           related_name='+',
                                           to='testplans.PlanType')),
            ],
            options={
                'verbose_name': 'historical test plan',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
    ]
