# Generated by Django 2.0.7 on 2018-07-07 21:07

from django.db import migrations, models


def forward_copy_data(apps, schema_editor):
    TestPlan = apps.get_model('testplans', 'TestPlan')
    TestPlanText = apps.get_model('testplans', 'TestPlanText')

    for test_plan in TestPlan.objects.all():
        latest_text = TestPlanText.objects.filter(plan=test_plan.pk).order_by('-pk').first()
        if latest_text:
            test_plan.plan_text = latest_text.plan_text
            test_plan.save()


class Migration(migrations.Migration):

    dependencies = [
        ('testplans', '0016_historicaltestplan'),
    ]

    operations = [
        # add new field to hold TP text but use a temporary name
        # b/c `text` is also the name of the pre-existing reverse relationship
        migrations.AddField(
            model_name='historicaltestplan',
            name='plan_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='testplan',
            name='plan_text',
            field=models.TextField(blank=True),
        ),

        # copy the data from the related model
        migrations.RunPython(forward_copy_data),

        # remove the related model
        migrations.RemoveField(
            model_name='testplantext',
            name='author',
        ),
        migrations.RemoveField(
            model_name='testplantext',
            name='plan',
        ),
        migrations.DeleteModel(
            name='TestPlanText',
        ),

        # rename the new field to what is inside the model source
        migrations.RenameField(
            model_name='historicaltestplan',
            old_name='plan_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='testplan',
            old_name='plan_text',
            new_name='text',
        ),
    ]
