# Generated by Django 2.1 on 2018-08-21 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testplans', '0017_move_text_into_testplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envplanmap',
            name='group',
        ),
        migrations.RemoveField(
            model_name='envplanmap',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='testplan',
            name='env_group',
        ),
        migrations.DeleteModel(
            name='EnvPlanMap',
        ),
    ]
