# Generated by Django 2.1.2 on 2018-10-06 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testplans', '0018_remove_env'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testplantag',
            name='user',
        ),
    ]
