# Generated by Django 2.0 on 2017-12-29 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkreference', '0002_make_url_a_urlfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkreference',
            name='object_pk',
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, verbose_name='object ID'),
        ),
        migrations.AlterIndexTogether(
            name='linkreference',
            index_together=set(),
        ),
        migrations.RemoveField(
            model_name='linkreference',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='linkreference',
            name='site',
        ),
    ]
