# Generated by Django 2.0.6 on 2018-06-29 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkreference', '0004_make_object_pk_foreign_key'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='linkreference',
            table=None,
        ),
    ]
