# Generated by Django 2.1.2 on 2018-10-18 11:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('testcases', '0002_squashed'),
    ]

    # important: this stays as an empty migration for now
    # it is already applied in version 6.1 and in the next version
    # operations have been moved to earlier migrations which will not
    # affect existing installations but will benefit future ones
    # where we can squash the migrations
    operations = []
