# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 12:54
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0009_testcasebug_rename_report_url_to_base_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='arguments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='requirement',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='script',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='summary',
            field=models.CharField(max_length=255),
        ),
    ]
