# Generated by Django 2.0 on 2017-12-30 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0010_update_blank_and_null_constraints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcaseattachment',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='testcaseattachment',
            name='case',
        ),
        migrations.RemoveField(
            model_name='testcaseattachment',
            name='case_run',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='attachment',
        ),
        migrations.DeleteModel(
            name='TestCaseAttachment',
        ),
    ]
