# Generated by Django 2.2.4 on 2019-08-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0010_remove_bug'),
    ]

    operations = [
        migrations.AlterField(model_name='bugsystem',
                              name='validate_reg_exp',
                              field=models.CharField(max_length=128,
                                                     help_text='A valid JavaScript regular '
                                                               'expression such as ^\\d$',
                                                     verbose_name='RegExp for ID validation',
                                                     default='')),
        migrations.AlterField(model_name='bugsystem',
                              name='url_reg_exp',
                              field=models.CharField(max_length=8192,
                                                     help_text='A valid Python format string such '
                                                               'as http://bugs.example.com/%s',
                                                     verbose_name='URL format string',
                                                     default='')),
        migrations.RemoveField(
            model_name='bugsystem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='bugsystem',
            name='url_reg_exp',
        ),
        migrations.RemoveField(
            model_name='bugsystem',
            name='validate_reg_exp',
        ),
    ]
