# Generated by Django 2.0.1 on 2018-02-01 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0011_delete_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='tag',
            field=models.ManyToManyField(related_name='case',
                                         through='testcases.TestCaseTag',
                                         to='management.TestTag'),
        ),
    ]
