# Generated by Django 3.0.2 on 2020-01-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0012_remove_autofield_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltestcase',
            name='create_date',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
