# Generated by Django 2.0.3 on 2018-03-13 21:35
from datetime import timedelta
from django.db import migrations, models


def forward(apps, schema_editor):
    TestCase = apps.get_model('testcases', 'TestCase')

    for tc in TestCase.objects.all():
        tc.estimated_time_new = timedelta(seconds=tc.estimated_time)
        tc.save()


def reverse(apps, schema_editor):
    TestCase = apps.get_model('testcases', 'TestCase')

    for tc in TestCase.objects.all():
        tc.estimated_time = tc.estimated_time_new.total_seconds()
        tc.save()


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0015_rename_testcasebug'),
    ]

    operations = [
        # add a timedelta field
        migrations.AddField(
            model_name='testcase',
            name='estimated_time_new',
            field=models.DurationField(default=timedelta(0)),
        ),
        # migrate the values
        migrations.RunPython(forward, reverse),
        # remove the integer field
        migrations.RemoveField(
            model_name='testcase',
            name='estimated_time',
        ),
        # rename the new field to the old name
        migrations.RenameField(
            model_name='testcase',
            old_name='estimated_time_new',
            new_name='estimated_time',
        ),
    ]
