# Generated by Django 3.1.4 on 2020-12-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testcases", "0016_testcasestatus_is_confirmed"),
    ]

    operations = [
        migrations.RenameField(
            model_name="testcaseemailsettings",
            old_name="auto_to_case_run_assignee",
            new_name="auto_to_execution_assignee",
        ),
        migrations.AlterField(
            model_name="testcase",
            name="plan",
            field=models.ManyToManyField(
                related_name="cases",
                through="testcases.TestCasePlan",
                to="testplans.TestPlan",
            ),
        ),
    ]
