# Generated by Django 2.0.4 on 2018-04-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0016_duration_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcasetext',
            name='action_checksum',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='testcasetext',
            name='breakdown_checksum',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='testcasetext',
            name='effect_checksum',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='testcasetext',
            name='setup_checksum',
            field=models.CharField(max_length=64),
        ),
    ]
