# Generated by Django 2.0.6 on 2018-06-26 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0017_increase_checksum_fields_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcasetext',
            name='action_checksum',
        ),
        migrations.RemoveField(
            model_name='testcasetext',
            name='breakdown_checksum',
        ),
        migrations.RemoveField(
            model_name='testcasetext',
            name='effect_checksum',
        ),
        migrations.RemoveField(
            model_name='testcasetext',
            name='setup_checksum',
        ),
    ]
