# Generated by Django 2.0.7 on 2018-07-16 07:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testcases', '0019_drop_meta_db_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTestCase',
            fields=[
                ('case_id', models.IntegerField(blank=True, db_index=True)),
                ('create_date', models.DateTimeField(blank=True,
                                                     db_column='creation_date',
                                                     editable=False)),
                ('is_automated', models.IntegerField(db_column='isautomated', default=0)),
                ('is_automated_proposed', models.BooleanField(default=False)),
                ('script', models.TextField(blank=True, null=True)),
                ('arguments', models.TextField(blank=True, null=True)),
                ('extra_link', models.CharField(blank=True,
                                                default=None,
                                                max_length=1024,
                                                null=True)),
                ('summary', models.CharField(max_length=255)),
                ('requirement', models.CharField(blank=True, max_length=255, null=True)),
                ('alias', models.CharField(blank=True, max_length=255)),
                ('estimated_time', models.DurationField(default=datetime.timedelta(0))),
                ('notes', models.TextField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'),
                                                           ('~', 'Changed'),
                                                           ('-', 'Deleted')],
                                                  max_length=1)),
                ('author', models.ForeignKey(blank=True,
                                             db_constraint=False,
                                             null=True,
                                             on_delete=django.db.models.deletion.DO_NOTHING,
                                             related_name='+',
                                             to=settings.AUTH_USER_MODEL)),
                ('case_status', models.ForeignKey(blank=True,
                                                  db_constraint=False,
                                                  null=True,
                                                  on_delete=django.db.models.deletion.DO_NOTHING,
                                                  related_name='+',
                                                  to='testcases.TestCaseStatus')),
                ('category', models.ForeignKey(blank=True,
                                               db_constraint=False,
                                               null=True,
                                               on_delete=django.db.models.deletion.DO_NOTHING,
                                               related_name='+',
                                               to='testcases.Category')),
                ('default_tester', models.ForeignKey(blank=True,
                                                     db_constraint=False,
                                                     null=True,
                                                     on_delete=django.db.models.deletion.DO_NOTHING,
                                                     related_name='+',
                                                     to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True,
                                                   on_delete=django.db.models.deletion.SET_NULL,
                                                   related_name='+',
                                                   to=settings.AUTH_USER_MODEL)),
                ('priority', models.ForeignKey(blank=True,
                                               db_constraint=False,
                                               null=True,
                                               on_delete=django.db.models.deletion.DO_NOTHING,
                                               related_name='+',
                                               to='management.Priority')),
                ('reviewer', models.ForeignKey(blank=True,
                                               db_constraint=False,
                                               null=True,
                                               on_delete=django.db.models.deletion.DO_NOTHING,
                                               related_name='+',
                                               to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical test case',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.AlterField(
            model_name='testcase',
            name='case_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
