# Generated by Django 2.0.7 on 2018-07-16 12:57

from django.db import migrations, models


def forward_copy_data(apps, schema_editor):
    TestCaseEmailSettings = apps.get_model('testcases', 'TestCaseEmailSettings')
    Contact = apps.get_model('testcases', 'Contact')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Site = apps.get_model('sites', 'Site')

    content_type = ContentType.objects.get_for_model(TestCaseEmailSettings)
    site = Site.objects.get_current()

    for email_settings in TestCaseEmailSettings.objects.all():
        contacts = Contact.objects.filter(
            content_type=content_type.pk,
            object_pk=email_settings.case.pk,
            site=site.pk).all()

        new_cc = []
        for contact in contacts:
            new_cc.append(contact.email)

        email_settings.new_cc_list = ','.join(new_cc)
        email_settings.save()


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0020_historicaltestcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcaseemailsettings',
            name='new_cc_list',
            field=models.TextField(default=''),
        ),
        migrations.RunPython(forward_copy_data),

        migrations.AlterIndexTogether(
            name='contact',
            index_together=set(),
        ),
        migrations.RemoveField(
            model_name='contact',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='site',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),

        migrations.RenameField(
            model_name='testcaseemailsettings',
            old_name='new_cc_list',
            new_name='cc_list',
        ),
    ]
