# Generated by Django 2.1.2 on 2018-10-03 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0021_convert_cc_list_to_string'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltestcase',
            name='estimated_time',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='estimated_time',
        ),
    ]
