# Generated by Django 5.2.9 on 2026-01-04 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("testcases", "0022_alter_historicaltemplate_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["name"], "verbose_name_plural": "Categories"},
        ),
    ]
