# Generated by Django 5.1.11 on 2025-07-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testcases", "0022_alter_historicaltemplate_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bugsystem",
            name="api_access_key",
            field=models.CharField(
                blank=True,
                help_text="Optional API token or access key used for authentication. Takes precedence over username/password if provided.",
                max_length=256,
                null=True,
                verbose_name="API access key",
            ),
        ),
    ]
