# Generated by Django 5.2.11 on 2026-02-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0023_alter_category_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltestcase',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='testcase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
