# Generated by Django 5.2.15 on 2026-06-14 15:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testcases", "0023_alter_category_ordering"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaltestcase",
            name="extra_link",
            field=models.URLField(
                blank=True,
                default=None,
                max_length=1024,
                null=True,
                validators=[
                    django.core.validators.URLValidator(
                        schemes=["http", "https", "ftp", "ftps"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="testcase",
            name="extra_link",
            field=models.URLField(
                blank=True,
                default=None,
                max_length=1024,
                null=True,
                validators=[
                    django.core.validators.URLValidator(
                        schemes=["http", "https", "ftp", "ftps"]
                    )
                ],
            ),
        ),
    ]
