# Generated by Django 6.0.7 on 2026-09-04 17:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testcases", "0024_alter_testcase_extra_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bugsystem",
            name="api_url",
            field=models.URLField(
                blank=True,
                help_text="This is the URL to which API requests will be sent. Leave empty to disable!",
                max_length=1024,
                null=True,
                validators=[
                    django.core.validators.URLValidator(schemes=["http", "https"])
                ],
                verbose_name="API URL",
            ),
        ),
        migrations.AlterField(
            model_name="bugsystem",
            name="base_url",
            field=models.URLField(
                blank=True,
                help_text=(
                    "Base URL, for example <strong>https://bugzilla.example.com</strong>!\n"
                    "Leave empty to disable!\n"
                ),
                max_length=1024,
                null=True,
                validators=[
                    django.core.validators.URLValidator(schemes=["http", "https"])
                ],
                verbose_name="Base URL",
            ),
        ),
    ]
