# Generated by Django 2.0.7 on 2018-07-25 14:45

from django.conf import settings
from django.db import migrations, models


class NoExceptionRunSQL(migrations.RunSQL):
    """
        Try to remove an SQL table but don't fail if it
        doesn't exist.

        We need this class because not all DB backends support
        `IF EXISTS` and because when creating the DB schema initially
        this table isn't present.

        This is all result from renaming a badly named app and can be removed
        after several versions when everyone has upgraded!
    """
    def _run_sql(self, schema_editor, sqls):
        try:
            super()._run_sql()
        except:  # nosec # noqa
            pass


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # remove old table before app rename,
        NoExceptionRunSQL('DROP TABLE "tcms_auth_useractivationkey";'),

        migrations.CreateModel(
            name='UserActivationKey',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False,
                                        verbose_name='ID')),
                ('activation_key', models.CharField(blank=True, max_length=64, null=True)),
                ('key_expires', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=models.deletion.CASCADE,
                                           to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
