# Generated by Django 2.0.7 on 2018-07-25 14:09

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('xmlrpc', '0001_initial'), ('xmlrpc', '0002_remove_xmlrpclog')]

    initial = True
