# Generated by Django 2.0.7 on 2018-07-18 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xmlrpc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xmlrpclog',
            name='user',
        ),
        migrations.DeleteModel(
            name='XmlRpcLog',
        ),
    ]
