# Generated by Django 2.0 on 2017-12-30 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_delete_attachments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tcmsenvvalue',
            options={'ordering': ['property__name', 'value']},
        ),
    ]
