# Generated by Django 3.0.9 on 2020-08-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0007_remove_autofield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
