# Generated by Django 3.1.4 on 2021-01-02 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0008_increase_product_name_size"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="build",
            options={
                "ordering": ["name"],
                "verbose_name": "Build",
                "verbose_name_plural": "Builds",
            },
        ),
    ]
