# Generated by Django 2.0.2 on 2018-02-15 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_rename_testtag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestone',
            name='product',
        ),
        migrations.RemoveField(
            model_name='build',
            name='milestone',
        ),
        migrations.RemoveField(
            model_name='product',
            name='default_milestone',
        ),
        migrations.RemoveField(
            model_name='product',
            name='milestone_url',
        ),
        migrations.DeleteModel(
            name='Milestone',
        ),
    ]
