# Generated by Django 2.0.2 on 2018-02-15 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_remove_milestone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='disallow_new',
        ),
        migrations.RemoveField(
            model_name='product',
            name='max_vote_super_bug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='vote_super_user',
        ),
        migrations.RemoveField(
            model_name='product',
            name='votes_to_confirm',
        ),
    ]
