# Generated by Django 3.2.6 on 2021-08-26 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0009_build_to_version"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="priority",
            options={"ordering": ["value"], "verbose_name_plural": "Priorities"},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={
                "ordering": ["name"],
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
            },
        ),
    ]
