# Generated by Django 2.0.6 on 2018-06-29 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_remove_unused_fields_from_product'),
    ]

    atomic = False

    operations = [
        migrations.AlterModelTable(
            name='build',
            table=None,
        ),
        migrations.AlterModelTable(
            name='classification',
            table=None,
        ),
        migrations.AlterModelTable(
            name='component',
            table=None,
        ),
        migrations.AlterModelTable(
            name='envgroup',
            table=None,
        ),
        migrations.AlterModelTable(
            name='envgrouppropertymap',
            table=None,
        ),
        migrations.AlterModelTable(
            name='envproperty',
            table=None,
        ),
        migrations.AlterModelTable(
            name='envvalue',
            table=None,
        ),
        migrations.AlterModelTable(
            name='priority',
            table=None,
        ),
        migrations.AlterModelTable(
            name='product',
            table=None,
        ),
        migrations.AlterModelTable(
            name='tag',
            table=None,
        ),
        migrations.AlterModelTable(
            name='version',
            table=None,
        ),
    ]
