# Generated by Django 5.2.9 on 2025-12-17 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0011_history_for_product_version_build"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="classification",
            options={
                "ordering": ["name"],
                "verbose_name": "Classification",
                "verbose_name_plural": "Classifications",
            },
        ),
        migrations.AlterModelOptions(
            name="component",
            options={
                "ordering": ["name"],
                "verbose_name": "Component",
                "verbose_name_plural": "Components",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalproduct",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Product",
                "verbose_name_plural": "historical Products",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalversion",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Version",
                "verbose_name_plural": "historical Versions",
            },
        ),
        migrations.AlterModelOptions(
            name="priority",
            options={
                "ordering": ["value"],
                "verbose_name": "Priority",
                "verbose_name_plural": "Priorities",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name"],
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.AlterModelOptions(
            name="version",
            options={
                "ordering": ["value"],
                "verbose_name": "Version",
                "verbose_name_plural": "Versions",
            },
        ),
    ]
