# Generated by Django 2.0.7 on 2018-07-05 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_drop_meta_db_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envgroup',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='envgroup',
            name='modified_by',
        ),
    ]
