# Generated by Django 2.1 on 2018-08-21 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testruns', '0017_remove_env'),
        ('testplans', '0018_remove_env'),
        ('management', '0012_remove_user_fks_from_envgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envgroup',
            name='property',
        ),
        migrations.RemoveField(
            model_name='envgrouppropertymap',
            name='group',
        ),
        migrations.RemoveField(
            model_name='envgrouppropertymap',
            name='property',
        ),
        migrations.AlterUniqueTogether(
            name='envvalue',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='envvalue',
            name='property',
        ),
        migrations.DeleteModel(
            name='EnvGroup',
        ),
        migrations.DeleteModel(
            name='EnvGroupPropertyMap',
        ),
        migrations.DeleteModel(
            name='EnvProperty',
        ),
        migrations.DeleteModel(
            name='EnvValue',
        ),
    ]
