# Generated by Django 2.0.7 on 2018-07-25 14:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('tcms.core.contrib.auth', '0001_initial'),
                ('tcms.core.contrib.auth', '0002_increase_activation_key_size'),
                ('tcms.core.contrib.auth', '0003_rename_useractivatekey')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivationKey',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False,
                                        verbose_name='ID')),
                ('activation_key', models.CharField(blank=True, max_length=64, null=True)),
                ('key_expires', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=models.deletion.CASCADE,
                                           to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
