# Generated by Django 2.0.4 on 2018-04-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcms.core.contrib.auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivatekey',
            name='activation_key',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
