# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models
from django.core.management.sql import emit_post_migrate_signal

def initial_data(apps, schema_editor):
    data = [
 {u'fields': {u'name': u'Tester',
              u'permissions': [188,
                               189,
                               190,
                               185,
                               186,
                               187,
                               38,
                               39,
                               35,
                               36,
                               41,
                               42,
                               22,
                               23,
                               194,
                               195,
                               25,
                               28,
                               26,
                               29,
                               13,
                               173,
                               174,
                               182,
                               183,
                               44,
                               45,
                               56,
                               57,
                               53,
                               54,
                               50,
                               51,
                               47,
                               48,
                               89,
                               90,
                               98,
                               99,
                               92,
                               93,
                               95,
                               96,
                               101,
                               102,
                               83,
                               84,
                               86,
                               87,
                               62,
                               63,
                               65,
                               66,
                               68,
                               69,
                               71,
                               72,
                               77,
                               78,
                               74,
                               75,
                               80,
                               81,
                               82,
                               59,
                               60,
                               209,
                               210,
                               206,
                               207,
                               200,
                               201,
                               197,
                               198,
                               203,
                               204,
                               218,
                               219,
                               16,
                               17,
                               113,
                               114,
                               122,
                               123,
                               131,
                               132,
                               133,
                               191,
                               192,
                               110,
                               111,
                               125,
                               126,
                               127,
                               221,
                               222,
                               119,
                               120,
                               121,
                               107,
                               108,
                               128,
                               129,
                               130,
                               116,
                               117,
                               137,
                               138,
                               152,
                               153,
                               149,
                               150,
                               215,
                               216,
                               217,
                               224,
                               225,
                               143,
                               144,
                               146,
                               147,
                               155,
                               156,
                               157,
                               140,
                               141,
                               134,
                               135,
                               167,
                               168,
                               170,
                               171,
                               212,
                               213,
                               214,
                               164,
                               165,
                               166,
                               161,
                               162,
                               158,
                               159,
                               160,
                               179,
                               180,
                               181,
                               176,
                               177,
                               178,
                               32,
                               33]},
  u'pk': 1},
 {u'fields': {u'name': u'Administrator',
              u'permissions': [188,
                               189,
                               190,
                               185,
                               186,
                               187,
                               38,
                               39,
                               35,
                               36,
                               41,
                               42,
                               22,
                               23,
                               4,
                               5,
                               10,
                               11,
                               1,
                               2,
                               7,
                               8,
                               194,
                               195,
                               25,
                               28,
                               26,
                               29,
                               30,
                               13,
                               14,
                               173,
                               174,
                               182,
                               183,
                               44,
                               45,
                               56,
                               57,
                               53,
                               54,
                               50,
                               51,
                               47,
                               48,
                               89,
                               90,
                               98,
                               99,
                               92,
                               93,
                               95,
                               96,
                               101,
                               102,
                               83,
                               84,
                               86,
                               87,
                               62,
                               63,
                               65,
                               66,
                               68,
                               69,
                               71,
                               72,
                               77,
                               78,
                               74,
                               75,
                               80,
                               81,
                               82,
                               59,
                               60,
                               209,
                               210,
                               206,
                               207,
                               200,
                               201,
                               197,
                               198,
                               203,
                               204,
                               218,
                               219,
                               16,
                               17,
                               19,
                               20,
                               113,
                               114,
                               122,
                               123,
                               131,
                               132,
                               133,
                               191,
                               192,
                               110,
                               111,
                               125,
                               126,
                               127,
                               221,
                               222,
                               119,
                               120,
                               121,
                               107,
                               108,
                               128,
                               129,
                               130,
                               116,
                               117,
                               137,
                               138,
                               152,
                               153,
                               149,
                               150,
                               215,
                               216,
                               217,
                               224,
                               225,
                               143,
                               144,
                               146,
                               147,
                               155,
                               156,
                               157,
                               140,
                               141,
                               134,
                               135,
                               167,
                               168,
                               170,
                               171,
                               212,
                               213,
                               214,
                               164,
                               165,
                               166,
                               161,
                               162,
                               158,
                               159,
                               160,
                               179,
                               180,
                               181,
                               176,
                               177,
                               178,
                               32,
                               33]},
  u'pk': 2},
 {u'fields': {u'name': u'default',
              u'permissions': [25,
                               28,
                               26,
                               27,
                               212,
                               213,
                               214,
                               164,
                               165,
                               166,
                               161,
                               162,
                               163,
                               158,
                               159,
                               160,
                               179,
                               180,
                               181,
                               176,
                               177,
                               178]},
  u'pk': 3},
 {u'fields': {u'name': u'System Admin', u'permissions': [8]},
  u'pk': 4}
    ]

    # this is supposed to create all permissions for all apps
    # but after it is executed Permission.objects.count() == 0
    # see https://code.djangoproject.com/ticket/23422#comment:20
    db_alias = schema_editor.connection.alias
    emit_post_migrate_signal([], 2, False, db_alias)


    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    for record in data:
        G = Group(name=record['fields']['name'])
        G.pk = record['pk']
        G.save()
        for p in record['fields']['permissions']:
# TODO: assign permissions to groups, see above
# and also use permission names, not IDs
#            G.permissions.add(Permission.objects.get(pk=p))
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '__latest__'),
        ('contenttypes', '__latest__'),
        ('sites', '__latest__'),
        ('testcases', '__latest__'),
        ('testplans', '__latest__'),
        ('testruns', '__latest__'),
    ]

    operations = [
        migrations.RunPython(initial_data),
    ]
