# Generated by Django 2.0.7 on 2018-07-25 14:15

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('logs', '0001_initial'),
                ('logs', '0002_drop_meta_db_name'),
                ('logs', '0003_drop_tcmslogmodel')]

    initial = True
