# Generated by Django 2.0.7 on 2018-07-16 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_drop_meta_db_name'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='tcmslogmodel',
            index_together=set(),
        ),
        migrations.RemoveField(
            model_name='tcmslogmodel',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='tcmslogmodel',
            name='site',
        ),
        migrations.RemoveField(
            model_name='tcmslogmodel',
            name='who',
        ),
        migrations.DeleteModel(
            name='TCMSLogModel',
        ),
    ]
