apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: beat-kiwi-tcm
  name: beat-kiwi-tcm
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: beat-kiwi-tcm
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: beat-kiwi-tcm
    spec:
      containers:
        - env:
            - name: KIWI_DB_ENGINE
              value: django.db.backends.postgresql
            - name: KIWI_DB_HOST
              value: db
            - name: KIWI_DB_NAME
              value: kiwi
            - name: KIWI_DB_PASSWORD
              value: kiwi
            - name: KIWI_DB_PORT
              value: "5432"
            - name: KIWI_DB_USER
              value: kiwi
          image: kiwitcms/kiwi:latest
          name: kiwi-web
          ports:
            - containerPort: 8080
            - containerPort: 8443
          resources: {}
          volumeMounts:
            - mountPath: /Kiwi/uploads
              name: uploads
      restartPolicy: Always
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: uploads
status: {}
