# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-14 15:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import tcms.core.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('testruns', '0003_testrun_estimated_time_remove_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrun',
            name='estimated_time',
            field=tcms.core.models.fields.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='testruntag',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='testruns.TestRun'),
        ),
    ]
