# Generated by Django 2.0.1 on 2018-02-01 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testruns', '0005_alter_testrun_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrun',
            name='tag',
            field=models.ManyToManyField(related_name='run',
                                         through='testruns.TestRunTag',
                                         to='management.TestTag'),
        ),
    ]
