# Generated by Django 3.0.2 on 2020-01-20 19:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testruns', '0007_test_execution_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testruncc',
            name='user',
            field=models.ForeignKey(on_delete=models.deletion.CASCADE,
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
