# Generated by Django 2.0.6 on 2018-06-26 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testruns', '0010_duration_field'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testrun',
            unique_together={('run_id', 'product_version')},
        ),
        migrations.RemoveField(
            model_name='testrun',
            name='plan_text_version',
        ),
    ]
