# Generated by Django 2.0.6 on 2018-06-29 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testruns', '0011_remove_plan_text_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcaserunstatus',
            name='auto_blinddown',
        ),
        migrations.RemoveField(
            model_name='testcaserunstatus',
            name='description',
        ),
        migrations.RemoveField(
            model_name='testcaserunstatus',
            name='sortkey',
        ),
    ]
