# Generated by Django 2.0.6 on 2018-06-29 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testruns', '0012_drop_fields_from_testcaserunstatus'),
    ]

    atomic = False

    operations = [
        migrations.AlterModelTable(
            name='envrunvaluemap',
            table=None,
        ),
        migrations.AlterModelTable(
            name='testcaserun',
            table=None,
        ),
        migrations.AlterModelTable(
            name='testcaserunstatus',
            table=None,
        ),
        migrations.AlterModelTable(
            name='testrun',
            table=None,
        ),
        migrations.AlterModelTable(
            name='testruncc',
            table=None,
        ),
        migrations.AlterModelTable(
            name='testruntag',
            table=None,
        ),
    ]
