# Generated by Django 2.0.7 on 2018-07-16 07:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testruns', '0013_drop_meta_db_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTestCaseRun',
            fields=[
                ('case_run_id', models.IntegerField(blank=True, db_index=True)),
                ('case_text_version', models.IntegerField()),
                ('running_date', models.DateTimeField(blank=True, null=True)),
                ('close_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('sortkey', models.IntegerField(blank=True, null=True)),
                ('environment_id', models.IntegerField(default=0)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'),
                                                           ('~', 'Changed'),
                                                           ('-', 'Deleted')],
                                                  max_length=1)),
                ('assignee', models.ForeignKey(blank=True,
                                               db_constraint=False,
                                               null=True,
                                               on_delete=models.deletion.DO_NOTHING,
                                               related_name='+',
                                               to=settings.AUTH_USER_MODEL)),
                ('build', models.ForeignKey(blank=True,
                                            db_constraint=False,
                                            null=True,
                                            on_delete=models.deletion.DO_NOTHING,
                                            related_name='+',
                                            to='management.Build')),
                ('case', models.ForeignKey(blank=True,
                                           db_constraint=False,
                                           null=True,
                                           on_delete=models.deletion.DO_NOTHING,
                                           related_name='+',
                                           to='testcases.TestCase')),
                ('case_run_status', models.ForeignKey(blank=True,
                                                      db_constraint=False,
                                                      null=True,
                                                      on_delete=models.deletion.DO_NOTHING,
                                                      related_name='+',
                                                      to='testruns.TestCaseRunStatus')),
                ('history_user', models.ForeignKey(null=True,
                                                   on_delete=models.deletion.SET_NULL,
                                                   related_name='+',
                                                   to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(blank=True,
                                          db_constraint=False,
                                          null=True,
                                          on_delete=models.deletion.DO_NOTHING,
                                          related_name='+',
                                          to='testruns.TestRun')),
                ('tested_by', models.ForeignKey(blank=True,
                                                db_constraint=False,
                                                null=True,
                                                on_delete=models.deletion.DO_NOTHING,
                                                related_name='+',
                                                to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical test case run',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
    ]
