# Generated by Django 3.2.8 on 2021-10-27 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("testruns", "0014_remove_auto_setting_start_date"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="testexecution",
            unique_together=set(),
        ),
    ]
