# Generated by Django 2.0.7 on 2018-07-18 13:13

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testruns', '0002_squashed'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTestRun',
            fields=[
                ('run_id', models.IntegerField(blank=True, db_index=True)),
                ('start_date', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('stop_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('summary', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('estimated_time', models.DurationField(default=datetime.timedelta(0))),
                ('environment_id', models.IntegerField(default=0)),
                ('auto_update_run_status', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'),
                                                           ('~', 'Changed'),
                                                           ('-', 'Deleted')],
                                                  max_length=1)),
                ('build', models.ForeignKey(blank=True,
                                            db_constraint=False,
                                            null=True,
                                            on_delete=models.deletion.DO_NOTHING,
                                            related_name='+',
                                            to='management.Build')),
                ('default_tester', models.ForeignKey(blank=True,
                                                     db_constraint=False,
                                                     null=True,
                                                     on_delete=models.deletion.DO_NOTHING,
                                                     related_name='+',
                                                     to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True,
                                                   on_delete=models.deletion.SET_NULL,
                                                   related_name='+',
                                                   to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True,
                                              db_constraint=False,
                                              null=True,
                                              on_delete=models.deletion.DO_NOTHING,
                                              related_name='+',
                                              to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True,
                                           db_constraint=False,
                                           null=True,
                                           on_delete=models.deletion.DO_NOTHING,
                                           related_name='+',
                                           to='testplans.TestPlan')),
                ('product_version', models.ForeignKey(blank=True,
                                                      db_constraint=False,
                                                      null=True,
                                                      on_delete=models.deletion.DO_NOTHING,
                                                      related_name='+',
                                                      to='management.Version')),
            ],
            options={
                'verbose_name': 'historical test run',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
    ]
