# Generated by Django 2.0.7 on 2018-07-19 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testruns', '0015_historicaltestrun'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltestrun',
            name='auto_update_run_status',
        ),
        migrations.RemoveField(
            model_name='testrun',
            name='auto_update_run_status',
        ),
    ]
