# Generated by Django 2.1.2 on 2018-10-03 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testruns', '0017_remove_env'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltestrun',
            name='estimated_time',
        ),
        migrations.RemoveField(
            model_name='testrun',
            name='estimated_time',
        ),
    ]
