# Generated by Django 5.2.15 on 2026-06-12 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "management",
            "0012_alter_classification_options_alter_component_options_and_more",
        ),
        ("testruns", "0019_alter_testexecutionstatus_color"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestExecutionTag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="testruns.testexecution",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="management.tag"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="testexecution",
            name="tag",
            field=models.ManyToManyField(
                related_name="execution",
                through="testruns.TestExecutionTag",
                to="management.tag",
            ),
        ),
    ]
